In [ ]:
# AUTOGRAD

In [1]:
import torch

In [3]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
print(y.grad_fn)

In [13]:
z = y + y * 3
out = x.mean()
print(z)
print(out)

tensor([[12., 12.],
        [12., 12.]], grad_fn=<AddBackward0>)
tensor(1., grad_fn=<MeanBackward0>)


In [14]:
print(out)

tensor(1., grad_fn=<MeanBackward0>)
