# Linear Regression 1D

In [1]:
import torch


In [4]:
# Define w = 2 and b = -1 for y = wx + b

w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

def forward(x):
    yhat = w * x + b
    return yhat

forward(torch.tensor([[1.0]]))

tensor([[1.]], grad_fn=<AddBackward0>)

In [9]:
x = torch.tensor([[1.0],[2.0]])
forward(x)
print('shape: ', forward(x).shape)
print('dimension: ', forward(x).ndimension())

shape:  torch.Size([2, 1])
dimension:  2


### Class Linear

In [10]:
from torch.nn import Linear

In [11]:
# Set random seed
torch.manual_seed(1)


In [27]:
lr = Linear(in_features=1, out_features=1, bias=True)
print(list(lr.parameters()))
print(lr.state_dict())
print(lr.state_dict().keys())
print(lr.state_dict().values())

print('weight: ', lr.weight)
print('bias: ', lr.bias)

x = torch.tensor([[1.0], [2.0]])
print('prediction: ', lr(x))

[Parameter containing:
tensor([[0.2794]], requires_grad=True), Parameter containing:
tensor([0.9486], requires_grad=True)]
OrderedDict([('weight', tensor([[0.2794]])), ('bias', tensor([0.9486]))])
odict_keys(['weight', 'bias'])
odict_values([tensor([[0.2794]]), tensor([0.9486])])
weight:  Parameter containing:
tensor([[0.2794]], requires_grad=True)
bias:  Parameter containing:
tensor([0.9486], requires_grad=True)
prediction:  tensor([[1.2279],
        [1.5073]], grad_fn=<AddmmBackward>)


### Build Custom Modules

In [28]:
from torch import nn


In [29]:
# Customize regression class

class LR(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        
        # Inherit from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
        
    # Prediction function
    def forward(self, x):
        out = self.linear(x)
        return out
    

In [37]:
# Linear regression model

lr = LR(1,1)
print(list(lr.parameters()))
print(lr.linear)

x = torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print('prediction: ', yhat)
print('dict: ', lr.state_dict())
print('keys: ', lr.state_dict().keys())
print('values: ', lr.state_dict().values())

[Parameter containing:
tensor([[-0.5308]], requires_grad=True), Parameter containing:
tensor([0.2941], requires_grad=True)]
Linear(in_features=1, out_features=1, bias=True)
prediction:  tensor([[-0.2367],
        [-0.7675],
        [-1.2984]], grad_fn=<AddmmBackward>)
dict:  OrderedDict([('linear.weight', tensor([[-0.5308]])), ('linear.bias', tensor([0.2941]))])
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.5308]]), tensor([0.2941])])
