In [ ]:
# 2d Tensor

In [5]:
import matplotlib as plt
import numpy as np
import pandas as pd
import torch

In [2]:
# Convert python list to tensors

td = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
tnsr_td = torch.tensor(td)
print("2 Dimensional List: ", td)
print("2 Dimensional Tensor: \n", tnsr_td)

2 Dimensional List:  [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
2 Dimensional Tensor: 
 tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [8]:
print("dimension: ", tnsr_td.ndimension())
print("size: ", tnsr_td.size())
print("shape: ", tnsr_td.shape)
print("dimension: ", tnsr_td.numel())

dimension:  2
size:  torch.Size([3, 3])
shape:  torch.Size([3, 3])
dimension:  9


In [9]:
# Pandas Data frame

df = pd.DataFrame({'a':[11,21,31],'b':[12,22,312]})
print(df)

    a    b
0  11   12
1  21   22
2  31  312


In [10]:
# Convert pandas DataFrame to Tensor

ts_df = torch.tensor(df.values)
print(ts_df)

tensor([[ 11,  12],
        [ 21,  22],
        [ 31, 312]])


In [13]:
ab = torch.tensor([[1,2,3],[1,2,3]])
ab.size()
print(ab)
print(ab.ndimension())

tensor([[1, 2, 3],
        [1, 2, 3]])
2


In [12]:
cd = torch.tensor([[1,0], [0,1]])
ef = torch.tensor([[2,1], [1,2]])
gh = cd * ef
print(gh)

tensor([[2, 0],
        [0, 2]])
