# Datasets

- Simple Datasets
- Transforms
- Compose



The `torch.manual_seed()` is for forcing the random function to give the same number every time we try to recompile it.

In [2]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)

### Simple Dataset

In [12]:
class toy_set(Dataset):
    
    #constructor with defaul values
    def __init__(self, length = 100, transform = None):
        self.len = length
        self.x = 2 * torch.ones(length, 1)
        self.y = torch.ones(length, 1)
        self.transform = transform
       
    # Getter
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    # Get Length
    def __len__(self):
        return self.len       

In [18]:
ds = toy_set()
# print(ds[0])
# print(ds.len)
# print(len(ds))

# for i in range(ds.len):
#     print(ds[i])

x, y = ds[0]

print(x, y)

tensor([2.]) tensor([1.])


# Transforms

create class for transforming data

In [31]:
class add_mult(object):
    
    # constructor
    def __init__(self, addx = 1, muly = 2):
        self.addx = addx
        self.muly = muly
        
    # executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        return sample

In [28]:
a_m = add_mult()
# print(a_m)

ds = toy_set(transform = a_m)
# print(ds.len)

for i in range(ds.len - 97):
    x, y = ds[i]
    print(x, y)

tensor([3.]) tensor([2.])
tensor([3.]) tensor([2.])
tensor([3.]) tensor([2.])


# Compose

compose transforms

In [34]:
from torchvision import transforms

class mult(object):
    
    # constructor
    def __init__(self, mult = 100):
        self.mult = mult
        
    # executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x * self.mult
        y = y * self.mult
        sample = x, y
        return sample
    
# combine add_mult() class and mult() class

# dt for data_transform
dt = transforms.Compose([mult(), add_mult()])
# print(dt)

print(ds[0])
print(dt(ds[0]))



(tensor([3.]), tensor([2.]))
(tensor([301.]), tensor([400.]))
